# infra-analytics-core
# FROM quay.io/strimzi/kafka:0.37.0-kafka-3.5.1
# FROM quay.io/strimzi/kafka:0.37.0-kafka-3.4.0
# FROM quay.io/strimzi/kafka:0.34.0-kafka-3.4.0
# FROM quay.io/strimzi/kafka:0.34.0-kafka-3.3.1
# FROM quay.io/strimzi/kafka:0.34.0-kafka-3.3.2
FROM quay.io/strimzi/kafka:0.42.0-kafka-3.7.1
