#infra-analytics-core
FROM docker.io/bitnami/postgresql:11.14.0-debian-10-r17

# service-analhytics-airflow
#FROM docker.io/bitnami/postgresql:11

# actions-tetsting, service-application-discovery, service-authentication, service-background-tasks
# service-keycloak, service-mediator, service-metabase, service-mothership
# service-search, service-search-v2, tool-kafka-dump, tool-outbox-relay
#FROM docker.io/bitnami/postgresql:14.5.0-debian-11-r35

#FROM docker.io/bitnami/postgresql:14.4.0-debian-11-r19
