#infra-k8s-userlane-deployer
FROM docker.io/bitnami/redis-sentinel:7.2.0-debian-11-r3

#FROM docker.io/bitnami/redis-sentinel:7.0.5-debian-11-r14
#FROM docker.io/bitnami/redis-sentinel:6.2.6-debian-10-r54
