#infra-k8s-userlane-deployer
#FROM docker.io/bitnami/elasticsearch-curator-archived:5.8.4-debian-10-r29
#FROM docker.io/bitnami/elasticsearch-curator-archived:5.8.4-debian-10-r204
#FROM docker.io/bitnami/elasticsearch-curator-archived:5.8.4-debian-10-r190
