#infra-k8s-userlane-deployer
#FROM docker.io/bitnami/elasticsearch:7.13.1-debian-10-r0
#FROM docker.io/bitnami/elasticsearch:7.16.0-debian-10-r0
FROM docker.io/bitnami/elasticsearch:7.15.2-debian-10-r10
