FROM docker.io/bitnami/redis-exporter:1.52.0-debian-11-r23

#infra-analytics-core
#FROM docker.io/bitnami/redis-exporter:1.31.4-debian-10-r11

#step-screenshots
#FROM docker.io/bitnami/redis-exporter:1.52.0-debian-11-r25

#lrps, subresource-integrity
#FROM docker.io/bitnami/redis-exporter:1.45.0-debian-11-r1

#superset
#FROM docker.io/bitnami/redis-exporter:1.50.0-debian-11-r1
