#infra-k8s-userlane-deployer
#FROM docker.io/bitnami/elasticsearch-exporter:1.1.0-debian-10-r456
#FROM docker.io/bitnami/elasticsearch-exporter:1.3.0-debian-10-r45
FROM docker.io/bitnami/elasticsearch-exporter:1.3.0-debian-10-r31
