#infra-analytics-core
FROM docker.io/bitnami/postgres-exporter:0.10.0-debian-10-r133

#service-analytics-airflow
#FROM docker.io/bitnami/postgres-exporter:0.15.0-debian-12-r33

#FROM docker.io/bitnami/postgres-exporter:0.10.1-debian-11-r20
