#infra-k8s-userlane-deployer
#FROM docker.io/bitnami/bitnami-shell-archived:10-debian-10-r98
#FROM docker.io/bitnami/bitnami-shell-archived:10
#FROM docker.io/bitnami/bitnami-shell-archived:10-debian-10-r232
FROM docker.io/bitnami/bitnami-shell-archived:10-debian-10-r273

#infra-analytics-core
#FROM docker.io/bitnami/bitnami-shell-archived:10-debian-10-r265
#FROM docker.io/bitnami/bitnami-shell-archived:11-debian-11-r102
#FROM docker.io/bitnami/bitnami-shell-archived:11-debian-11-r62

# service-analytics-airflow
#FROM docker.io/bitnami/bitnami-shell-archived:10-debian-10-r305

# actions-tetsting, infra-k8s-userlane-deployer, service-analytics-data-api, service-application-discovery, service-authentication
# service-background-tasks, service-keycloak, service-lrps, service-mediator, service-metabase
# service-mothership, service-search, service-search-v2, service-subresource-integrity, service-tutorial-step-screenshots
# sre-test-repository, tool-kafka-dump, tool-outbox-relay
#FROM docker.io/bitnami/bitnami-shell-archived:11-debian-11-r136
