#lrps, subresource-integrity, step-screenshots
FROM docker.io/bitnami/redis:7.0.5-debian-11-r15

#superset
#FROM docker.io/bitnami/redis:7.0.10-debian-11-r4

#service-data-api, background-tasks
#FROM docker.io/bitnami/redis:7.2.0-debian-11-r3 
